/*
 * Copyright (c) 2014. Vishal Siramshetty
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.unibonn.vishal.ui;

import de.unibonn.vishal.main.DrawMolecule;
import de.unibonn.vishal.main.PopUpMenu;
import java.awt.Dimension;
import java.awt.GraphicsConfiguration;
import java.awt.Rectangle;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.openscience.cdk.exception.CDKException;

/**
 *
 * @author Vishal Siramshetty <srmshtty[at]gmail.com>
 */
public class SmileViz extends javax.swing.JFrame {

    PopUpMenu popup = null;

    /**
     * Creates new form SmileViz
     */
    public SmileViz() {
        initComponents();
        resultDisplayPanel.setToolTipText(null);
        imageLabel.setToolTipText(null);
        outerPanel.setToolTipText(null);
        inputSmile.setToolTipText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outerPanel = new javax.swing.JPanel();
        inputSmile = new javax.swing.JTextField();
        resultDisplayPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        statusBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMILES Visualizer");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("outerFrame"); // NOI18N
        setResizable(false);

        outerPanel.setToolTipText("");

        inputSmile.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        inputSmile.setToolTipText("");
        inputSmile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSmileKeyReleased(evt);
            }
        });

        resultDisplayPanel.setBackground(java.awt.Color.white);
        resultDisplayPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resultDisplayPanel.setToolTipText("");

        imageLabel.setToolTipText("");
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout resultDisplayPanelLayout = new javax.swing.GroupLayout(resultDisplayPanel);
        resultDisplayPanel.setLayout(resultDisplayPanelLayout);
        resultDisplayPanelLayout.setHorizontalGroup(
            resultDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultDisplayPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        resultDisplayPanelLayout.setVerticalGroup(
            resultDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        infoLabel.setText("Type your SMILES here");

        javax.swing.GroupLayout outerPanelLayout = new javax.swing.GroupLayout(outerPanel);
        outerPanel.setLayout(outerPanelLayout);
        outerPanelLayout.setHorizontalGroup(
            outerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultDisplayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputSmile, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(outerPanelLayout.createSequentialGroup()
                        .addComponent(infoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        outerPanelLayout.setVerticalGroup(
            outerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSmile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSmileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSmileKeyReleased

        DrawMolecule drawer = new DrawMolecule();
        String query = inputSmile.getText().trim();
        if (!query.isEmpty()) {
            try {
                ImageIcon icon = drawer.getImageIcon(query, imageLabel.getWidth(), imageLabel.getHeight());
                imageLabel.setIcon(icon);
                statusBar.setText("<html><b>Status</b>: Successful!");
                popup = new PopUpMenu(query, icon);
                imageLabel.setComponentPopupMenu(popup);
            } catch (CDKException ex) {
                if (ex.getMessage().contains("^")) {
                    statusBar.setText("<html><b>Status</b>: Error! " + getFirstErrorLine(ex.getMessage())
                            + " " + getRingClosureError(ex.getMessage()));
                } else {
                    statusBar.setText("<html><b>Status</b>: Error! " + ex.getMessage());
                }
                imageLabel.setIcon(null);
            }
        } else {
            imageLabel.setIcon(null);
            statusBar.setText(null);
        }

    }//GEN-LAST:event_inputSmileKeyReleased

    private String getFirstErrorLine(String error) {
        String newline = System.getProperty("line.separator");
        String[] lines = error.split(newline);
        if (lines.length > 0) {
            for (int i = 0; i < lines.length; i++) {
                if (i == 0) {
                    return lines[i];
                }
            }
        }
        return null;
    }

    private String getRingClosureError(String error) {
        String newline = System.getProperty("line.separator");
        String[] lines = error.split(newline);

        if (lines.length > 0) {
            for (int i = 0; i < lines.length; i++) {
                if (i == 1) {
                    int index = getErrorIndex(error);
                    char c = lines[i].charAt(index - 1);
                    String smiles = lines[i].substring(0, lines[i].length() - 1);

                    StringBuilder smile = new StringBuilder();
                    smile.append(smiles).append("<u>").append(c).append("</u>");

                    return smile.toString();
                }
            }
        }
        return null;

    }

    private String generateHTMLSpace(int n) {
        String space = "&nbsp;";
        StringBuilder htmlSpace = new StringBuilder();
        for (int i = 0; i < n; i++) {
            htmlSpace.append(space);
        }

        return htmlSpace.toString();

    }

    private int getErrorIndex(String error) {
        int index = -1;
        String newline = System.getProperty("line.separator");
        String pipe = "^";
        String[] lines = error.split(newline);

        if (lines.length > 0) {
            for (String line : lines) {
                if (line.contains(pipe)) {
                    return line.indexOf(pipe) + 1;

                }
            }
        }

        return index;
    }

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked

        if (evt.isPopupTrigger()) {
            if (popup != null) {
                popup.show(imageLabel, evt.getX(), evt.getY());

            }
        }

    }//GEN-LAST:event_imageLabelMouseClicked

    // add a listener for dynamically generating new images from updated SMILES
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmileViz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SmileViz ui = new SmileViz();
                ui.setVisible(true);
                GraphicsConfiguration gc = ui.getGraphicsConfiguration();
                Rectangle bounds = gc.getBounds();
                Dimension size = ui.getPreferredSize();
                ui.setLocation((int) ((bounds.width / 2) - (size.getWidth() / 2)),
                        (int) ((bounds.height / 2) - (size.getHeight() / 2)));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField inputSmile;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JPanel resultDisplayPanel;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables
}
